# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: TestDevelopment

on:
  push:
    branches: [ "dev" ]
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./vld.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Platform=Win32 -target:vld ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 -target:vld ${{env.SOLUTION_FILE_PATH}}

    - name: Run x64 Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./bin/tests/x64/Debug/basics.exe
