name: TestDevelopment

on:
  push:
    branches: [ "dev" ]
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./vld.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build VLD Win64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration="Debug(Release)" /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Run tests
      uses: microsoft-approved-actions/vstest@master
      with:
        testAssembly: ms_static_string*.dll
        searchFolder: './bin/tests/x64/debug(release)/'
