name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
 build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.2
      with:
        versionSpec: '6.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Platform=Win32 -target:vld ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 -target:vld ${{env.SOLUTION_FILE_PATH}}

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: ./setup/vld-setup.iss
        options: /V0 /O+ /DMyAppVersion=${{ env.GitVersion_MajorMinorPatch }}

    - uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: ./Output/vld-${{ env.GitVersion_MajorMinorPatch }}-setup.exe
        retention-days: 1
